services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 cdr_portal.wsgi:application
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - "8000"
